# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More spceificall, we're going yo cover:
* Introduction to tensors
* getting information from tensors
* Manipulating tensors
* Tensros & NumPY
* Using @tf.functions (a way to speed up yout regular Python functions)
* Using GPUs with TensorFlow (or TPU's)
* Exercises to try yourself

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create tensorws with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[2.,3.,3.],[3.,2.,1.],[.34,3.,2.]])
matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.  , 3.  , 3.  ],
       [3.  , 2.  , 1.  ],
       [0.34, 3.  , 2.  ]], dtype=float32)>

In [7]:
matrix.ndim

2

In [8]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6 ]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]],
                      [[19,20,21],
                       [22,23,24]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])>

In [9]:
tensor.ndim # regardin the shape lenght

3